# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('description', models.TextField(max_length=500)),
                ('total_calls', models.IntegerField()),
                ('response_time', models.DecimalField(decimal_places=1, max_digits=10)),
                ('location', models.CharField(max_length=26)),
                ('picture_link', models.URLField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
